import type { Metadata } from "next";
import { JetBrains_Mono, Inter, Geist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/footer/Footer";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    /* We add the variables to the body className */
    <html
      lang="en"
      className={cn(jetbrains.variable, "font-sans", geist.variable)}
      suppressHydrationWarning
    >
      <body className=" font-sans antialiased">
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
